export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_ERROR = "GET_ORGANIZATION_ERROR";

export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_ERROR = "CREATE_ORGANIZATION_ERROR";

export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_ERROR = "UPDATE_ORGANIZATION_ERROR";

export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_ERROR = 'FORGOT_ERROR';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';
export const CHANGE_PASS_ERROR = 'CHANGE_PASS_ERROR';

export const CHANGE_ORG_PASS_SUCCESS = 'CHANGE_ORG_PASS_SUCCESS';
export const CHANGE_ORG_PASS_REQUEST = 'CHANGE_ORG_PASS_REQUEST';
export const CHANGE_ORG_PASS_ERROR = 'CHANGE_ORG_PASS_ERROR';

export const GET_ORG_PROFILE_REQUEST = 'GET_ORG_PROFILE_REQUEST';
export const GET_ORG_PROFILE_SUCCESS = 'GET_ORG_PROFILE_SUCCESS';
export const GET_ORG_PROFILE_ERROR = 'GET_ORG_PROFILE_ERROR';

export const UPDATE_ORG_PROFILE_REQUEST = 'UPDATE_ORG_PROFILE_REQUEST';
export const UPDATE_ORG_PROFILE_SUCCESS = 'UPDATE_ORG_PROFILE_SUCCESS';
export const UPDATE_ORG_PROFILE_ERROR = 'UPDATE_ORG_PROFILE_ERROR';

export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR';

export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_ERROR = 'GET_ROLE_ERROR';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR';

export const GET_SPECIALITIES_REQUEST = 'GET_SPECIALITIES_REQUEST';
export const GET_SPECIALITIES_SUCCESS = 'GET_SPECIALITIES_SUCCESS';
export const GET_SPECIALITIES_ERROR = 'GET_SPECIALITIES_ERROR';

export const CREATE_SPECIALITIES_REQUEST = 'CREATE_SPECIALITIES_REQUEST';
export const CREATE_SPECIALITIES_SUCCESS = 'CREATE_SPECIALITIES_SUCCESS';
export const CREATE_SPECIALITIES_ERROR = 'CREATE_SPECIALITIES_ERROR';

export const UPDATE_SPECIALITIES_REQUEST = 'UPDATE_SPECIALITIES_REQUEST';
export const UPDATE_SPECIALITIES_SUCCESS = 'UPDATE_SPECIALITIES_SUCCESS';
export const UPDATE_SPECIALITIES_ERROR = 'UPDATE_SPECIALITIES_ERROR';

export const DELETE_SPECIALITIES_REQUEST = 'DELETE_SPECIALITIES_REQUEST';
export const DELETE_SPECIALITIES_SUCCESS = 'DELETE_SPECIALITIES_SUCCESS';
export const DELETE_SPECIALITIES_ERROR = 'DELETE_SPECIALITIES_ERROR';

export const GET_STAFF_REQUEST = 'GET_STAFF_REQUEST';
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS';
export const GET_STAFF_ERROR = 'GET_STAFF_ERROR';

export const CREATE_STAFF_REQUEST = 'CREATE_STAFF_REQUEST';
export const CREATE_STAFF_SUCCESS = 'CREATE_STAFF_SUCCESS';
export const CREATE_STAFF_ERROR = 'CREATE_STAFF_ERROR';

export const UPDATE_STAFF_REQUEST = 'UPDATE_STAFF_REQUEST';
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS';
export const UPDATE_STAFF_ERROR = 'UPDATE_STAFF_ERROR';

export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_ERROR = 'DELETE_STAFF_ERROR';

export const GET_TRUST_REQUEST = "GET_TRUST_REQUEST";
export const GET_TRUST_SUCCESS = "GET_TRUST_SUCCESS";
export const GET_TRUST_ERROR = "GET_TRUST_ERROR"

export const CREATE_TRUST_REQUEST = "CREATE_TRUST_REQUEST";
export const CREATE_TRUST_SUCCESS = "CREATE_TRUST_SUCCESS";
export const CREATE_TRUST_ERROR = "CREATE_TRUST_ERROR"

export const UPDATE_TRUST_REQUEST = "UPDATE_TRUST_REQUEST";
export const UPDATE_TRUST_SUCCESS = "UPDATE_TRUST_SUCCESS";
export const UPDATE_TRUST_ERROR = "UPDATE_TRUST_ERROR"

export const DELETE_TRUST_REQUEST = "DELETE_TRUST_REQUEST";
export const DELETE_TRUST_SUCCESS = "DELETE_TRUST_SUCCESS";
export const DELETE_TRUST_ERROR = "DELETE_TRUST_ERROR"

export const GET_BOOKING_REQUEST = "GET_BOOKING_REQUEST";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_ERROR = "GET_BOOKING_ERROR"

export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR"

export const UPDATE_BOOKING_REQUEST = "UPDATE_BOOKING_REQUEST";
export const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
export const UPDATE_BOOKING_ERROR = "UPDATE_BOOKING_ERROR"

export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_ERROR = "DELETE_BOOKING_ERROR"

export const GET_SIGNEE_REQUETS = "GET_SIGNEE_REQUETS"
export const GET_SIGNEE_SUCCESS = "GET_SIGNEE_SUCCESS"
export const GET_SIGNEE_ERROR = "GET_SIGNEE_ERROR"

export const CREATE_SIGNEE_REQUETS = "CREATE_SIGNEE_REQUETS"
export const CREATE_SIGNEE_SUCCESS = "CREATE_SIGNEE_SUCCESS"
export const CREATE_SIGNEE_ERROR = "CREATE_SIGNEE_ERROR"

export const UPDATE_SIGNEE_REQUETS = "UPDATE_SIGNEE_REQUETS"
export const UPDATE_SIGNEE_SUCCESS = "UPDATE_SIGNEE_SUCCESS"
export const UPDATE_SIGNEE_ERROR = "UPDATE_SIGNEE_ERROR"

export const GET_CANDIDATE_REFERRED_FROM_SUCCESS = "GET_CANDIDATE_REFERRED_FROM_SUCCESS"

export const GET_SINGLE_SIGNEE_REQUETS = "GET_SINGLE_SIGNEE_REQUETS"
export const GET_SINGLE_SIGNEE_SUCCESS = "GET_SINGLE_SIGNEE_SUCCESS"
export const GET_SINGLE_SIGNEE_ERROR = "GET_SINGLE_SIGNEE_ERROR"

export const DELETE_SIGNEE_REQUETS = "DELETE_SIGNEE_REQUETS"
export const DELETE_SIGNEE_SUCCESS = "DELETE_SIGNEE_SUCCESS"
export const DELETE_SIGNEE_ERROR = "DELETE_SIGNEE_ERROR"

// ------------------

export const CHANGE_STAFF_PASS_SUCCESS = 'CHANGE_STAFF_PASS_SUCCESS';
export const CHANGE_STAFF_PASS_REQUEST = 'CHANGE_STAFF_PASS_REQUEST';
export const CHANGE_STAFF_PASS_ERROR = 'CHANGE_STAFF_PASS_ERROR';

export const GET_STAFF_PROFILE_REQUEST = 'GET_STAFF_PROFILE_REQUEST';
export const GET_STAFF_PROFILE_SUCCESS = 'GET_STAFF_PROFILE_SUCCESS';
export const GET_STAFF_PROFILE_ERROR = 'GET_STAFF_PROFILE_ERROR';

export const UPDATE_STAFF_PROFILE_REQUEST = 'UPDATE_STAFF_PROFILE_REQUEST';
export const UPDATE_STAFF_PROFILE_SUCCESS = 'UPDATE_STAFF_PROFILE_SUCCESS';
export const UPDATE_STAFF_PROFILE_ERROR = 'UPDATE_STAFF_PROFILE_ERROR';

export const CONFIRM_BOOKING_REQUEST = "CONFIRM_BOOKING_REQUEST"
export const CONFIRM_BOOKING_SUCCESS = "CONFIRM_BOOKING_SUCCESS"
export const CONFIRM_BOOKING_ERROR = "CONFIRM_BOOKING_ERROR"

export const CHANGE_SHIFT_STATUS_REQUEST = "CHANGE_SHIFT_STATUS_REQUEST"
export const CHANGE_SHIFT_STATUS_SUCCESS = "CHANGE_SHIFT_STATUS_SUCCESS"
export const CHANGE_SHIFT_STATUS_ERROR = "CHANGE_SHIFT_STATUS_ERROR"

export const CHANGE_SIGNEE_PRO_STATUS_REQUEST = "CHANGE_SIGNEE_PRO_STATUS_REQUEST"
export const CHANGE_SIGNEE_PRO_STATUS_SUCCESS = "CHANGE_SIGNEE_PRO_STATUS_SUCCESS"
export const CHANGE_SIGNEE_PRO_STATUS_ERROR = "CHANGE_SIGNEE_PRO_STATUS_ERROR"

export const CHANGE_SIGNEE_COMP_STATUS_REQUEST = "CHANGE_SIGNEE_COMP_STATUS_REQUEST"
export const CHANGE_SIGNEE_COMP_STATUS_SUCCESS = "CHANGE_SIGNEE_COMP_STATUS_SUCCESS"
export const CHANGE_SIGNEE_COMP_STATUS_ERROR = "CHANGE_SIGNEE_COMP_STATUS_ERROR"

export const CHANGE_DOC_STATUS_REQUEST = "CHANGE_DOC_STATUS_REQUEST"
export const CHANGE_DOC_STATUS_SUCCESS = "CHANGE_DOC_STATUS_SUCCESS"
export const CHANGE_DOC_STATUS_ERROR = "CHANGE_DOC_STATUS_ERROR"

export const USER_INVITATION_REQUEST = "USER_INVITATION_REQUEST"
export const USER_INVITATION_SUCCESS = "USER_INVITATION_SUCCESS"
export const USER_INVITATION_ERROR = "USER_INVITATION_ERROR"

export const PUT_NOTIFY = 'PUT_NOTIFY';

export const ADD_NEW_NOTIFICATION_FAIL = "ADD_NEW_NOTIFICATION_FAIL";
export const ADD_NEW_NOTIFICATION_SUCCESS = "ADD_NEW_NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const ADD_NEW_LOADING_REQUEST = "ADD_NEW_LOADING_REQUEST";
export const ADD_NEW_LOADING_SUCCESS = "ADD_NEW_LOADING_SUCCESS";
export const ADD_NEW_LOADING_FAIL = "ADD_NEW_LOADING_FAIL";

export const CHANGE_PAYMENT_STATUS_REQUEST = "CHANGE_PAYMENT_STATUS_REQUEST";
export const CHANGE_PAYMENT_STATUS_SUCCESS = "CHANGE_PAYMENT_STATUS_SUCCESS";
export const CHANGE_PAYMENT_STATUS_ERROR = "CHANGE_PAYMENT_STATUS_ERROR";

export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";

export const GET_DASHBOARD_REQUEST = "GET_DASHBOARD_REQUEST";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_ERROR = "GET_DASHBOARD_ERROR";
