export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_ORGANIZATION_REQUEST = "GET_ORGANIZATION_REQUEST";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_ERROR = "GET_ORGANIZATION_ERROR";

export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";
export const CREATE_ORGANIZATION_ERROR = "CREATE_ORGANIZATION_ERROR";

export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_ERROR = "UPDATE_ORGANIZATION_ERROR";

export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_ERROR = 'FORGOT_ERROR';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';
export const CHANGE_PASS_ERROR = 'CHANGE_PASS_ERROR';

export const CHANGE_ORG_PASS_SUCCESS = 'CHANGE_ORG_PASS_SUCCESS';
export const CHANGE_ORG_PASS_REQUEST = 'CHANGE_ORG_PASS_REQUEST';
export const CHANGE_ORG_PASS_ERROR = 'CHANGE_ORG_PASS_ERROR';

export const GET_ORG_PROFILE_REQUEST = 'GET_ORG_PROFILE_REQUEST';
export const GET_ORG_PROFILE_SUCCESS = 'GET_ORG_PROFILE_SUCCESS';
export const GET_ORG_PROFILE_ERROR = 'GET_ORG_PROFILE_ERROR';

export const UPDATE_ORG_PROFILE_REQUEST = 'UPDATE_ORG_PROFILE_REQUEST';
export const UPDATE_ORG_PROFILE_SUCCESS = 'UPDATE_ORG_PROFILE_SUCCESS';
export const UPDATE_ORG_PROFILE_ERROR = 'UPDATE_ORG_PROFILE_ERROR';

export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR';

export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_ERROR = 'GET_ROLE_ERROR';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR';

export const GET_SPECIALITIES_REQUEST = 'GET_SPECIALITIES_REQUEST';
export const GET_SPECIALITIES_SUCCESS = 'GET_SPECIALITIES_SUCCESS';
export const GET_SPECIALITIES_ERROR = 'GET_SPECIALITIES_ERROR';

export const CREATE_SPECIALITIES_REQUEST = 'CREATE_SPECIALITIES_REQUEST';
export const CREATE_SPECIALITIES_SUCCESS = 'CREATE_SPECIALITIES_SUCCESS';
export const CREATE_SPECIALITIES_ERROR = 'CREATE_SPECIALITIES_ERROR';

export const UPDATE_SPECIALITIES_REQUEST = 'UPDATE_SPECIALITIES_REQUEST';
export const UPDATE_SPECIALITIES_SUCCESS = 'UPDATE_SPECIALITIES_SUCCESS';
export const UPDATE_SPECIALITIES_ERROR = 'UPDATE_SPECIALITIES_ERROR';


export const PUT_NOTIFY = 'PUT_NOTIFY';